// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Ghi đè biến môi trường hệ thống (vd. DATABASE_URL cũ trong Windows) bằng giá trị trong .env
config({ path: path.join(process.cwd(), ".env"), override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
