import "dotenv/config";
import { PrismaClient, SubmissionStatus } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

async function main() {
  // Seed categories
  const categories = await Promise.all([
    prisma.category.upsert({
      where: { slug: "game" },
      update: {},
      create: { name: "Game", slug: "game" },
    }),
    prisma.category.upsert({
      where: { slug: "utility" },
      update: {},
      create: { name: "Utility", slug: "utility" },
    }),
    prisma.category.upsert({
      where: { slug: "finance" },
      update: {},
      create: { name: "Finance", slug: "finance" },
    }),
    prisma.category.upsert({
      where: { slug: "productivity" },
      update: {},
      create: { name: "Productivity", slug: "productivity" },
    }),
    prisma.category.upsert({
      where: { slug: "social" },
      update: {},
      create: { name: "Social", slug: "social" },
    }),
  ]);

  // Seed demo admin user
  const admin = await prisma.user.upsert({
    where: { email: "admin@td.com" },
    update: {},
    create: {
      name: "TD Admin",
      email: "admin@td.com",
      isAdmin: true,
    },
  });

  // Seed demo contributor
  const contributor = await prisma.user.upsert({
    where: { email: "dev@example.com" },
    update: {},
    create: {
      name: "Demo Dev",
      email: "dev@example.com",
      isAdmin: false,
    },
  });

  // Seed approved mini-apps (displayed as "Modules" in the UI) — 40+ modules for testing pagination, leaderboard, etc.
  const approvedModules = [
    // High-vote modules (for leaderboard testing)
    {
      slug: "pomodoro-timer",
      name: "Pomodoro Timer",
      description: "A simple Pomodoro timer to help you stay focused. Built with vanilla JS. Supports custom work/break intervals and notifications.",
      repoUrl: "https://github.com/codecrafters-io/build-a-pomodoro-timer",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 87,
    },
    {
      slug: "2048-game",
      name: "2048 Game",
      description: "Classic 2048 puzzle game. Keyboard and touch support. Saves high score to localStorage. Responsive and fully playable.",
      repoUrl: "https://github.com/gabrielecirulli/2048",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "game")!.id,
      authorId: contributor.id,
      voteCount: 156,
    },
    {
      slug: "snake-game",
      name: "Snake Game",
      description: "Classic snake game with difficulty levels, score tracking, and fullscreen mode. Arrow keys or WASD to control.",
      repoUrl: "https://github.com/example/snake-game",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "game")!.id,
      authorId: contributor.id,
      voteCount: 102,
    },
    {
      slug: "todo-app",
      name: "Todo App",
      description: "Fully-featured todo list with categories, due dates, reminders, and local storage persistence. Perfect for task management.",
      repoUrl: "https://github.com/tastejs/todomvc",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 143,
    },
    {
      slug: "password-generator",
      name: "Password Generator",
      description: "Secure random password generator with customizable length, character types, and copy-to-clipboard functionality. Military-grade encryption.",
      repoUrl: "https://github.com/example/password-gen",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 67,
    },
    {
      slug: "expense-tracker",
      name: "Expense Tracker",
      description: "Track your daily expenses with categories and monthly summaries. Export to CSV. Pie charts for visualization.",
      repoUrl: "https://github.com/example/expense-tracker",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "finance")!.id,
      authorId: contributor.id,
      voteCount: 54,
    },
    {
      slug: "markdown-editor",
      name: "Markdown Editor",
      description: "Live-preview markdown editor with syntax highlighting. Based on Monaco editor. Supports themes and multiple export formats.",
      repoUrl: "https://github.com/example/md-editor",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 78,
    },
    {
      slug: "calculator",
      name: "Calculator",
      description: "Full-featured calculator with history, keyboard support, and theme switching. Handles complex mathematical expressions.",
      repoUrl: "https://github.com/example/calculator",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 92,
    },
    {
      slug: "color-picker",
      name: "Color Picker",
      description: "Advanced color picker with RGB, HSL, HEX support. Includes color history, gradient generator, and accessibility checker.",
      repoUrl: "https://github.com/example/color-picker",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 45,
    },
    {
      slug: "habit-tracker",
      name: "Habit Tracker",
      description: "Build and track daily habits with streak visualization. Browser notifications and weekly reports. Offline-first design.",
      repoUrl: "https://github.com/example/habit-tracker",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 73,
    },
    // More approved modules for pagination testing
    {
      slug: "url-shortener",
      name: "URL Shortener",
      description: "Shorten long URLs with custom aliases. QR code generation and analytics tracking.",
      repoUrl: "https://github.com/example/url-shortener",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 31,
    },
    {
      slug: "quote-generator",
      name: "Quote Generator",
      description: "Random quote generator with copy and share features. Integrates with Twitter API. Dark mode support.",
      repoUrl: "https://github.com/example/quote-gen",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 38,
    },
    {
      slug: "weather-app",
      name: "Weather App",
      description: "Real-time weather app using OpenWeather API. Shows hourly forecast, temperature trends, and weather alerts.",
      repoUrl: "https://github.com/example/weather-app",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 64,
    },
    {
      slug: "music-player",
      name: "Music Player",
      description: "Lightweight music player with playlist support, visualizer, and shuffle/repeat modes. Responsive and accessible.",
      repoUrl: "https://github.com/example/music-player",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "social")!.id,
      authorId: contributor.id,
      voteCount: 55,
    },
    {
      slug: "budget-planner",
      name: "Budget Planner",
      description: "Plan your monthly budget with automated savings goals and expense tracking. Gender-based financial insights.",
      repoUrl: "https://github.com/example/budget-planner",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "finance")!.id,
      authorId: contributor.id,
      voteCount: 48,
    },
    {
      slug: "timer-app",
      name: "Timer App",
      description: "Customizable countdown timer with preset times, notifications, and progress visualization.",
      repoUrl: "https://github.com/example/timer-app",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 39,
    },
    {
      slug: "json-formatter",
      name: "JSON Formatter",
      description: "Format, validate, and minify JSON. Supports tree view, diff comparison, and multiple export formats.",
      repoUrl: "https://github.com/example/json-formatter",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 41,
    },
    {
      slug: "memory-game",
      name: "Memory Game",
      description: "Classic memory card matching game with difficulty levels, timer, and score tracking.",
      repoUrl: "https://github.com/example/memory-game",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "game")!.id,
      authorId: contributor.id,
      voteCount: 68,
    },
    {
      slug: "note-app",
      name: "Note App",
      description: "Simple yet powerful note-taking app with categories, tags, and full-text search. Cloud sync optional.",
      repoUrl: "https://github.com/example/note-app",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 52,
    },
    {
      slug: "dice-simulator",
      name: "Dice Simulator",
      description: "Realistic dice roller with multiple dice types and statistics. Perfect for tabletop gaming.",
      repoUrl: "https://github.com/example/dice-simulator",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "game")!.id,
      authorId: contributor.id,
      voteCount: 44,
    },
    {
      slug: "qr-generator",
      name: "QR Code Generator",
      description: "Generate QR codes from text or URLs. Download as PNG/SVG. Supports custom colors and logos.",
      repoUrl: "https://github.com/example/qr-generator",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 56,
    },
    {
      slug: "tic-tac-toe",
      name: "Tic Tac Toe",
      description: "Classic tic-tac-toe game with AI opponent. Difficulty levels and move history.",
      repoUrl: "https://github.com/example/tic-tac-toe",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "game")!.id,
      authorId: contributor.id,
      voteCount: 49,
    },
    {
      slug: "unit-converter",
      name: "Unit Converter",
      description: "Convert between metric and imperial units. Temperature, length, weight, volume, and more.",
      repoUrl: "https://github.com/example/unit-converter",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 35,
    },
    {
      slug: "kanban-board",
      name: "Kanban Board",
      description: "Drag-and-drop kanban board for task management. Multiple columns, card details, and filtering.",
      repoUrl: "https://github.com/example/kanban-board",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 71,
    },
    {
      slug: "random-name-gen",
      name: "Random Name Generator",
      description: "Generate random names for characters, projects, and more. Multiple name types and cultures.",
      repoUrl: "https://github.com/example/random-name-gen",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 32,
    },
    {
      slug: "expense-splitter",
      name: "Expense Splitter",
      description: "Split expenses between friends. Calculate who owes whom and settle debts easily.",
      repoUrl: "https://github.com/example/expense-splitter",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "finance")!.id,
      authorId: contributor.id,
      voteCount: 51,
    },
    {
      slug: "code-snippet-saver",
      name: "Code Snippet Saver",
      description: "Save and organize code snippets with syntax highlighting. Search, filter, and export features.",
      repoUrl: "https://github.com/example/code-snippet-saver",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 83,
    },
    {
      slug: "drawing-canvas",
      name: "Drawing Canvas",
      description: "Free drawing application with brush tools, colors, and layers. Export as PNG or SVG.",
      repoUrl: "https://github.com/example/drawing-canvas",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 61,
    },
    {
      slug: "workout-timer",
      name: "Workout Timer",
      description: "HIIT workout timer with presets, intervals, and voice guidance. Perfect for fitness enthusiasts.",
      repoUrl: "https://github.com/example/workout-timer",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 46,
    },
    {
      slug: "language-translator",
      name: "Language Translator",
      description: "Translate text between 50+ languages. Audio pronunciation and offline dictionaries available.",
      repoUrl: "https://github.com/example/language-translator",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 74,
    },
  ];

  for (const mod of approvedModules) {
    await prisma.miniApp.upsert({
      where: { slug: mod.slug },
      update: { demoUrl: mod.demoUrl, voteCount: mod.voteCount },
      create: mod,
    });
  }

  // Seed pending submissions (for admin panel demo)
  const pendingModules = [
    {
      slug: "markdown-editor",
      name: "Markdown Editor",
      description:
        "Live-preview markdown editor with syntax highlighting. Based on CodeMirror.",
      repoUrl: "https://github.com/example/md-editor",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "habit-tracker",
      name: "Habit Tracker",
      description:
        "Build and track daily habits with streak visualization. Sends browser notifications.",
      repoUrl: "https://github.com/example/habit-tracker",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "weather-app",
      name: "Weather App",
      description: "Real-time weather app using OpenWeather API. Shows hourly forecast.",
      repoUrl: "https://github.com/example/weather-app",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "todo-list",
      name: "Todo List",
      description: "Simple yet powerful todo app with categories and local storage.",
      repoUrl: "https://github.com/example/todo-list",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "password-generator",
      name: "Password Generator",
      description: "Secure random password generator with customizable options and copy-to-clipboard.",
      repoUrl: "https://github.com/example/password-gen",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "music-player",
      name: "Music Player",
      description: "Lightweight music player with playlist support and visualizer.",
      repoUrl: "https://github.com/example/music-player",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "social")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "budget-planner",
      name: "Budget Planner",
      description: "Plan your monthly budget with automated savings goals and expense tracking.",
      repoUrl: "https://github.com/example/budget-planner",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "finance")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "snake-game",
      name: "Snake Game",
      description: "Classic snake game with difficulty levels and leaderboard.",
      repoUrl: "https://github.com/example/snake-game",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "game")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "note-taking",
      name: "Note Taking App",
      description: "Beautiful note-taking app with folders, tags, and markdown support.",
      repoUrl: "https://github.com/example/notes",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "color-palette",
      name: "Color Palette Generator",
      description: "Generate beautiful color palettes and export as CSS, JSON, or SCSS.",
      repoUrl: "https://github.com/example/color-gen",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "pomodoro-advanced",
      name: "Advanced Pomodoro Timer",
      description: "Pomodoro app with notifications, statistics, and dark mode.",
      repoUrl: "https://github.com/example/pomodoro-v2",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    // 10 additional pending modules for admin testing
    {
      slug: "email-template-builder",
      name: "Email Template Builder",
      description: "Drag-and-drop email template builder with preview and export to HTML.",
      repoUrl: "https://github.com/example/email-builder",
      demoUrl: null,
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "resume-builder",
      name: "Resume Builder",
      description: "Create professional resumes with templates, download as PDF.",
      repoUrl: "https://github.com/example/resume-builder",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "url-validator",
      name: "URL Validator",
      description: "Check if URLs are valid and accessible. Show headers, redirects, and status codes.",
      repoUrl: "https://github.com/example/url-validator",
      demoUrl: null,
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "image-compressor",
      name: "Image Compressor",
      description: "Compress images online without quality loss. Supports PNG, JPG, WebP formats.",
      repoUrl: "https://github.com/example/image-compressor",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "regex-tester",
      name: "Regex Tester",
      description: "Test and debug regular expressions with live matching and explanations.",
      repoUrl: "https://github.com/example/regex-tester",
      demoUrl: null,
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "task-scheduler",
      name: "Task Scheduler",
      description: "Schedule tasks and reminders with notifications and recurring events.",
      repoUrl: "https://github.com/example/task-scheduler",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "sudoku-solver",
      name: "Sudoku Solver",
      description: "Play sudoku and get hints. Solver with difficulty levels from easy to expert.",
      repoUrl: "https://github.com/example/sudoku",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "game")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "crypto-price-tracker",
      name: "Crypto Price Tracker",
      description: "Real-time cryptocurrency price tracker with charts and alerts.",
      repoUrl: "https://github.com/example/crypto-tracker",
      demoUrl: null,
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "finance")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "meditation-timer",
      name: "Meditation Timer",
      description: "Guided meditation timer with ambient sounds and calming visuals.",
      repoUrl: "https://github.com/example/meditation",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
    {
      slug: "blog-generator",
      name: "Blog Generator",
      description: "Create and manage blog posts with markdown editor, tags, and categories.",
      repoUrl: "https://github.com/example/blog-gen",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.PENDING,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 0,
    },
  ];

  for (const mod of pendingModules) {
    await prisma.miniApp.upsert({
      where: { slug: mod.slug },
      update: { demoUrl: mod.demoUrl },
      create: mod,
    });
  }

  // Additional approved modules (for Recently Reviewed section)
  const moreApprovedModules = [
    {
      slug: "calculator-plus",
      name: "Calculator Plus",
      description: "Advanced calculator with scientific functions and history.",
      repoUrl: "https://github.com/example/calc-plus",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 12,
      createdAt: new Date("2026-04-05"),
    },
    {
      slug: "quote-generator",
      name: "Random Quote Generator",
      description: "Fetch random quotes from API with copy-to-clipboard feature.",
      repoUrl: "https://github.com/example/quotes",
      demoUrl: null,
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 8,
      createdAt: new Date("2026-04-04"),
    },
    {
      slug: "workout-tracker",
      name: "Workout Tracker",
      description: "Track workouts with exercise library and progress charts.",
      repoUrl: "https://github.com/example/workout",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 15,
      createdAt: new Date("2026-04-03"),
    },
    {
      slug: "tic-tac-toe",
      name: "Tic Tac Toe Game",
      description: "Classic tic tac toe with AI opponent and play history.",
      repoUrl: "https://github.com/example/ttt",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "game")!.id,
      authorId: contributor.id,
      voteCount: 22,
      createdAt: new Date("2026-04-02"),
    },
    {
      slug: "crypto-converter",
      name: "Crypto Converter",
      description: "Real-time cryptocurrency converter with multiple exchanges.",
      repoUrl: "https://github.com/example/crypto",
      demoUrl: null,
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "finance")!.id,
      authorId: contributor.id,
      voteCount: 19,
      createdAt: new Date("2026-04-01"),
    },
    {
      slug: "recipe-finder",
      name: "Recipe Finder",
      description: "Search and save your favorite recipes with ingredients filter.",
      repoUrl: "https://github.com/example/recipes",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "social")!.id,
      authorId: contributor.id,
      voteCount: 28,
      createdAt: new Date("2026-03-31"),
    },
    {
      slug: "json-formatter",
      name: "JSON Formatter",
      description: "Format, validate and beautify JSON with syntax highlighting.",
      repoUrl: "https://github.com/example/json-fmt",
      demoUrl: null,
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 16,
      createdAt: new Date("2026-03-30"),
    },
    {
      slug: "memory-game",
      name: "Memory Game",
      description: "Classic memory matching game with difficulty levels.",
      repoUrl: "https://github.com/example/memory",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "game")!.id,
      authorId: contributor.id,
      voteCount: 32,
      createdAt: new Date("2026-03-29"),
    },
    {
      slug: "timer-stopwatch",
      name: "Timer & Stopwatch",
      description: "Simple timer and stopwatch with multiple modes.",
      repoUrl: "https://github.com/example/timer",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 11,
      createdAt: new Date("2026-03-28"),
    },
    {
      slug: "unit-converter",
      name: "Unit Converter",
      description: "Convert between different units of measurement instantly.",
      repoUrl: "https://github.com/example/units",
      demoUrl: null,
      status: SubmissionStatus.APPROVED,
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 14,
      createdAt: new Date("2026-03-27"),
    },
  ];

  for (const mod of moreApprovedModules) {
    await prisma.miniApp.upsert({
      where: { slug: mod.slug },
      update: {},
      create: mod,
    });
  }

  // Rejected modules (for Recently Reviewed section)
  const rejectedModules = [
    {
      slug: "rejected-broken-app",
      name: "Broken Weather Widget",
      description: "Weather widget with API issues.",
      repoUrl: "https://github.com/example/broken-weather",
      demoUrl: null,
      status: SubmissionStatus.REJECTED,
      feedback: "API endpoints not working. Please fix and resubmit.",
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 0,
      createdAt: new Date("2026-04-06"),
    },
    {
      slug: "rejected-incomplete",
      name: "Incomplete Todo",
      description: "Todo app that's not finished.",
      repoUrl: "https://github.com/example/incomplete-todo",
      demoUrl: null,
      status: SubmissionStatus.REJECTED,
      feedback: "Implementation is incomplete. Missing core features.",
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 0,
      createdAt: new Date("2026-04-05"),
    },
    {
      slug: "rejected-no-demo",
      name: "Game Without Demo",
      description: "A game with no working demo link.",
      repoUrl: "https://github.com/example/game-no-demo",
      demoUrl: null,
      status: SubmissionStatus.REJECTED,
      feedback: "Please provide a working demo link or hosted version.",
      categoryId: categories.find((c) => c.slug === "game")!.id,
      authorId: contributor.id,
      voteCount: 0,
      createdAt: new Date("2026-04-04"),
    },
    {
      slug: "rejected-poor-quality",
      name: "Low Quality App",
      description: "App with poor code structure.",
      repoUrl: "https://github.com/example/poor-quality",
      demoUrl: null,
      status: SubmissionStatus.REJECTED,
      feedback: "Code quality doesn't meet standards. Refactor and resubmit.",
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 0,
      createdAt: new Date("2026-04-03"),
    },
    {
      slug: "rejected-security",
      name: "Insecure Payment App",
      description: "Payment processor with security issues.",
      repoUrl: "https://github.com/example/insecure-payment",
      demoUrl: null,
      status: SubmissionStatus.REJECTED,
      feedback: "Security vulnerabilities detected. Please address before resubmitting.",
      categoryId: categories.find((c) => c.slug === "finance")!.id,
      authorId: contributor.id,
      voteCount: 0,
      createdAt: new Date("2026-04-02"),
    },
    {
      slug: "rejected-duplicate",
      name: "Duplicate Pomodoro Timer",
      description: "Basic pomodoro timer similar to existing features.",
      repoUrl: "https://github.com/example/dup-pomodoro",
      demoUrl: null,
      status: SubmissionStatus.REJECTED,
      feedback: "Too similar to existing Pomodoro Timer submission.",
      categoryId: categories.find((c) => c.slug === "productivity")!.id,
      authorId: contributor.id,
      voteCount: 0,
      createdAt: new Date("2026-04-01"),
    },
    {
      slug: "rejected-broken-links",
      name: "Missing Documentation",
      description: "App with missing repo documentation.",
      repoUrl: "https://github.com/example/missing-docs",
      demoUrl: null,
      status: SubmissionStatus.REJECTED,
      feedback: "Repository is missing README and documentation.",
      categoryId: categories.find((c) => c.slug === "social")!.id,
      authorId: contributor.id,
      voteCount: 0,
      createdAt: new Date("2026-03-31"),
    },
    {
      slug: "rejected-slow-performance",
      name: "Bloated App",
      description: "Performance-heavy application.",
      repoUrl: "https://github.com/example/bloated-app",
      demoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_NrLmx2ubTubTGlsf79l-gvcJE_5A1y3Maw&s",
      status: SubmissionStatus.REJECTED,
      feedback: "App loads too slowly. Optimize and resubmit.",
      categoryId: categories.find((c) => c.slug === "game")!.id,
      authorId: contributor.id,
      voteCount: 0,
      createdAt: new Date("2026-03-30"),
    },
    {
      slug: "rejected-no-responsiveness",
      name: "Non-Responsive Design",
      description: "App that doesn't work on mobile.",
      repoUrl: "https://github.com/example/no-mobile",
      demoUrl: null,
      status: SubmissionStatus.REJECTED,
      feedback: "App must be responsive on mobile devices.",
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 0,
      createdAt: new Date("2026-03-29"),
    },
    {
      slug: "rejected-licensing",
      name: "License Issues",
      description: "App with unclear licensing.",
      repoUrl: "https://github.com/example/no-license",
      demoUrl: null,
      status: SubmissionStatus.REJECTED,
      feedback: "Please include proper open source license in repository.",
      categoryId: categories.find((c) => c.slug === "utility")!.id,
      authorId: contributor.id,
      voteCount: 0,
      createdAt: new Date("2026-03-28"),
    },
  ];

  for (const mod of rejectedModules) {
    await prisma.miniApp.upsert({
      where: { slug: mod.slug },
      update: { demoUrl: mod.demoUrl },
      create: mod,
    });
  }

  console.log("✅ Seed complete");
  console.log(`   ${categories.length} categories`);
  console.log(`   ${approvedModules.length + moreApprovedModules.length} approved modules`);
  console.log(`   ${pendingModules.length} pending modules (for testing)`);
  console.log(`   ${rejectedModules.length} rejected modules (for testing)`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
